### PR TITLE
Added support for Doctrine 2 in Database Panel

### PR DESCRIPTION
**Pull request by Jadro007**
Not sure if it will work for projects without Doctrine 2, so it might need some additional changes

### CODE REVIEW

**Comment by Jadro007** [comment]
plus I found out that prepareBindings is broken for some queries (I think that the ones that contains nested arrays)

**Comment by recca0120** [comment]
HI Jadro007

thanks for you pr

can you offer me have any broken query...

I'll try to fix this bug without doctrine...

**Comment by Jadro007** [comment]
for example 
SELECT COUNT(p0_.id) AS sclr_0 FROM products p0_ INNER JOIN product_productColor p2_ ON p0_.id = p2_.product_id INNER JOIN categories c1_ ON c1_.id = p2_.productColor_id AND c1_.type IN ('2') **WHERE c1_.id IN (?)** ORDER BY p0_.count_of_orders DESCSELECT COUNT(p0_.id) AS sclr_0 FROM products p0_ INNER JOIN product_productColor p2_ ON p0_.id = p2_.product_id INNER JOIN categories c1_ ON c1_.id = p2_.productColor_id AND c1_.type IN ('2') WHERE c1_.id IN (?) ORDER BY p0_.count_of_orders DESC

I think problem is the part with WHERE c1_.id IN (?)
It fails on $sql = vsprintf($sql, $bindings); (around line 190 in DatabasePanel.php)
because $bindings contain nested array 
`array(1) { 
[0]=> array(2) { 
   [0]=> int(7) 
   [1]=> int(8) }
 }`

**Comment by recca0120** [comment]
hi @Jadro007 

try v1.6.2

**Comment by Jadro007** [comment]
works like charm :) good job, thanks

**Pull request closed without merging**
